FROM ubuntu:latest

ARG VERSION

RUN apt-get update && apt-get install -y wget \
    && wget -O /usr/local/bin/tianlicdn https://github.com/Tianli-CDN/cdn-server/releases/download/${VERSION}/tianlicdn-linux-amd64 \
    && chmod +x /usr/local/bin/tianlicdn \
    && apt-get install -y redis-server

WORKDIR /app

CMD sh -c "redis-server & sleep 10 && tianlicdn"
EXPOSE 5012