FROM ubuntu:latest

ARG VERSION

RUN apt-get update && apt-get install -y wget \
    && wget -O /usr/local/bin/tianlicdn https://github.com/Tianli-CDN/cdn-server/releases/download/${VERSION}/tianlicdn-linux-amd64 \
    && chmod +x /usr/local/bin/tianlicdn

WORKDIR /app

CMD ["tianlicdn"]

EXPOSE 5012